### ISSUE TITLE
help

### ISSUE THREAD

**Issue by BallisticOK** [zzazuu/ESXBase-server#1]
Resolved live-internal.fivem.net:30110 to 178.32.9.100:30110
Creating script environments fo
=================================================================
r _c    Native Crash Reporting
=================================================================
fGot a SIGSEGV while executing native code. This usually indicates
x_internal
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
=================================================================

=================================================================
FXServer crashed.
A minidump can be found at C:\FXServer_ESX\crashes\aaad595e-fd6e-4f6d-826e-2def22dd6df5.dmp.
Failed to automatically report the crash. Please submit the minidump to the project developers.

**Comment by ghost** [comment]
You need to update artifacts or the cfx data see fivem.net then go to make a sever under download fivem button.

**Comment by cserko93** [comment]
same for me after "updating".

**Comment by zzazuu** [comment]
You need to update artifacts, cfx-data and also Visual C++ you can find links for it https://docs.fivem.net/docs/server-manual/setting-up-a-server/
